config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get 'about', to:'pages#about'

  resources :articles do
    resources :comments
  end

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :article_categories, dependent: :destroy
	has_many :articles, through: :article_categories
	validates :name, presence: true, uniqueness: true, length: {minimum: 3, maximum: 25}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
before_action :set_category, only: [:edit, :update, :show]
before_action :require_user, except: [:show]
before_action :require_admin, except: [:show]



	def index
		@categories = Category.all
	end


	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:notice] = "Category added successfully"
			redirect_to categories_path
		else
			render 'new'
		end
	end

	def edit

	end

	def update
		if @category.update(category_params)
			flash[:notice] = "Category updated successfully"
			redirect_to categories_path
		else
			render 'edit'
		end
	end

	def show
		if params[:term]
			@articles = @category.articles.where('title like ?', "%#{params[:term]}%").order('created_at DESC').paginate(page: params[:page], per_page: 5)
		else
			@articles = @category.articles.order('created_at DESC').paginate(page: params[:page], per_page: 5)
		end
	end


	private
	def category_params
		params.require(:category).permit(:name)
	end

	def set_category
		@category = Category.find(params[:id])
	end

	def require_admin
			if !current_user.admin?
			flash[:notice] = "Only ADMIN can perform that action"
			redirect_to articles_path
		end
	end

end

app/views/categories/_form.html.erb
<%= render "shared/errors", obj: @category %>

<%= form_for @category do |f| %>
    <div class="form-group row">
        <%= f.label :name, class: "col-sm-2 col-form-label-lg" %>
        <div class="col-sm-6">
            <%= f.text_field :name, class: "form-control", placeholder: "Category Name" %>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-2">

        </div>

        <div class="col-sm-2">
            <%= f.submit nil, class: "btn", id: "article_button" %>
        </div>

    </div>

<% end %>

app/views/categories/edit.html.erb
<div class="container my-5">
    <h1 class="display-4 my-5"> Edit Category </h1>

    <%= render 'form' %>
</div>

app/views/categories/index.html.erb
<div class="container my-5">
  <%= link_to "New Category", new_category_path, class: "btn btn-success btn-lg mb-4" %>
  <table class="table table-striped table-dark">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Category</th>
        <th scope="col"> </th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category|%>
      <tr>
        <th scope="row"> <%= category.id %></th>
        <td> <%= category.name %> </td>
        <td> <%= link_to "Edit", edit_category_path(category), class: "btn btn-info btn-sm" %> </td>
      </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/categories/new.html.erb
<div class="container my-5">
    <h1 class="display-4 my-5"> New Category </h1>

    <%= render 'form' %>
</div>

app/views/categories/show.html.erb
<div class="container">

    <h1 class="display-4 my-5"> Category: <%= @category.name %> </h1>


    <%= form_tag(category_path, method: :get) do %>
        <div class="row my-5">
            <div class="col-sm-4">
            </div>
            <div class="col-sm-4">
                <div class="input-group mb-3">
                    <%= text_field_tag :term, params[:term], class: "form-control", placeholder: "Search by title"%>
                    <div class="input-group-append">
                        <%= submit_tag "Search", name: nil, class: "btn btn-outline-primary", id: "button-addon2" %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>


    <div id="pagination">
        <%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'pagination justify-content-center my-4') %>
    </div> 
    <% @articles.each do |article| %>
        <div class="alert my-5" id="article_panel">
            <h1 class="display-4"> <%= link_to article.title, article_path(article), id: "username_link" %> </h1>
            <p class="lead"> <%= truncate(article.description, length: 300) %> </p>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                    <small class="font-weight-bold"> Created by: </small>
                    <p> <%= link_to article.user.username, user_path(article.user) %> (<%= time_ago_in_words(article.created_at) %> ago) </p>
                </div>
                <div class="col-sm-3">
                    <small class="font-weight-bold"> Last Updated: </small>
                    <p> <%= time_ago_in_words(article.updated_at) %> ago</p>
                </div>
                <div class="col-sm-2"> </div>
                <% if article.categories.any? %>
                    <div class="col-sm-3">
                        <small class="font-weight-bold d-block"> Category </small>
                        <% article.categories.each do |category| %>
                           <p class="d-inline mr-2"> <%= link_to category.name, category_path(category) %> </p>
                        <%end%>
                    </div>
                <%end%>
            </div>
            <div>
                <h6> <%= pluralize(article.comments.count,'Comment') %> </h6>
            </div>
            <div class="d-block">
                <% if logged_in && (current_user == article.user || current_user.admin?) %>
                    <div class="d-inline-block mr-2">
                        <%= link_to "Edit", edit_article_path(article), class: "btn btn-info btn-sm" %>
                    </div>
                    <div class="d-inline-block mx-2">
                        <%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-sm" %>
                    </div>
                <%end%>
            </div>
        </div>
    <%end%>
    <div id="pagination">
        <%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'pagination justify-content-center my-4') %>
    </div> 
</div>