config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get 'about', to:'pages#about'

  resources :articles do
    resources :comments
  end

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

end

app/views/layouts/_messages.html.erb
<div class="container">
	<div class="alert alert-warning alert-dismissible fade show my-4" role="alert">
	  <% flash.each do |name,msg| %>
	  	<%= msg %>
	  <%end%>
	  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	    <span aria-hidden="true">&times;</span>
	  </button>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg">
  <%= link_to "Blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fa fa-bars"></i></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if current_page?(root_path) %>">
          <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(articles_path) %>">
        <%= link_to "Articles", articles_path, class: "nav-link" %>
      </li>

      <% if logged_in %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Create Article", new_article_path, class: "dropdown-item" %>
        </div>
      </li>
      <%end%>
      <li class="nav-item <%= 'active' if current_page?(users_path) %>">
        <%= link_to "Users", users_path, class: "nav-link" %>
      </li>
    </ul>

    <% if !logged_in %>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to "Log in", login_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign up", signup_path, class: "nav-link" %>
      </li>
    </ul>
    <% else %>
      <ul class="navbar-nav ml-auto">
      <% if current_user.admin? %>
        <li class="nav-item <%= 'active' if current_page?(categories_path) %>">
        <%= link_to "Categories Panel", categories_path, class: "nav-link" %>
        </li>
        <li class="nav-item"> <a class="lead nav-link btn btn-dark btn-sm disabled text-white"> ADMIN </a> </li>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.username %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Change Password", edit_user_path(current_user), class: "dropdown-item"%>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to "Log out", logout_path, method: :delete, class: "nav-link" %>
      </li>
    </ul>
    <%end%>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mysite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navigation' %>

    <% if !flash.empty? %>
      <%= render 'layouts/messages' %>
    <%end%>

    <%= yield %>

<!--     <div class="alert alert-info">
      <p> <%= debug(params) if Rails.env.development? %> </p>
    </div> -->

  </body>
</html>